############################################################
# docker-compose.yml - aplicación en node.js - Express
############################################################

version: "3"
services:
  api:
    build: ./api-fast-chat/
    restart: always
    depends_on:
      - db
    ports:
      - 8001:8001
    volumes:
      - .:/usr/src/app
    links:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres/pg_data:/data/db
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      POSTGRES_USER: docker
volumes:
  pg_data:
